language: 'ko-KR'
tone_instructions:
early_access: false
reviews:
  profile: 'chill'
  # 코드래빗이 자동으로 PR을 닫음
  request_changes_workflow: false
  # 코드래빗이 PR 내용을 요약
  high_level_summary: true
  auto_title_placeholder: '@coderabbitai [WEB-nn] 커밋 타입: 커밋 메세지'
  # 각 리뷰에 대한 상세 설명
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
