name: '🚨 이슈 생성'
description: '해야 할 일(태스크)을 적어주시면 Jira와 연동돼요.'
labels: [feat]
title: '[FEAT] 제목을 작성해주세요.'
body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ Jira Ticket Number'
      description: 'Jira 상에서 EPIC 단위의 상위 티켓 넘버를 적어주세요.'
      placeholder: 'WEB-00'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: '📝 description'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ Tasks'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: false
